###
# This file configures the project "Piper" pipeline of your project.
# For a reference of the configuration concept and available options, please have a look into its documentation.
#
# The documentation for the most recent pipeline version can always be found at:
#    https://sap.github.io/jenkins-library/
#
# This is a YAML-file. YAML is an indentation-sensitive file format. Please make sure to properly indent changes to it.
###



### General project setup
general:
  inferBuildTool: true
  pipeline: 'sap-cloud-sdk'    # this line is mandatory
  buildTool: 'mta'             # or 'npm' or 'maven'

### Step-specific configuration
steps:
  artifactPrepareVersion:
    versioningType: cloud_noTag
  mtaBuild:    
    buildTarget: 'CF'
### Stage-specific configuration
stages:
  Build:
    mavenExecuteStaticCodeChecks: true    # true, if you want to execute static code checks to verify the syntax of your Java code
    npmExecuteLint: true                  # true, if you want to run a lint check that verifies the syntax of your JavaScript code

  'Additional Unit Tests':
     npmExecuteScripts: true   # true, if you want to execute test scripts that are defined in step npmExecuteScripts

  Release:
    cloudFoundryDeploy: true   # true, if you want to deploy to Cloud Foundry. If you set this parameter to true, the CloudFoundryDeploy step is mandatory
    tmsUpload: true            # true if you want to upload your artifact to SAP Cloud Transport Management. If you set this parameter to true, the tmsUpload step is mandatory

cloudFoundryDeploy:
    cloudFoundry:
      credentialsId: 'cfdeploy'
      apiEndpoint: 'https://api.cf.eu10.hana.ondemand.com'
      org: 'dcafb7e5trial'
      space: 'prova'

npmExecuteScripts:    # only relevant, if you set the npmExecuteScripts parameter in the Additional Unit Tests stage to true
    runScripts: ['start']

    # tmsUpload: true            # true, if you want to upload your artifact to SAP Cloud Transport Management

#  Integration:
#    credentials:
#      - alias: 'mySystemAlias'
#        credentialId: 'mySystemCredentialsId'

# Release:
#     cfTargets:
#       - org: 'myOrg'
#         space: 'mySpace'
#         apiEndpoint: 'https://'
#         appName: 'myAppName'
#         manifest: 'manifest.yml'
#         credentialsId: 'myDeploymentCredentialsId'




